apiVersion: apps/v1
kind: Deployment
metadata:
  name: wineinfo-frontend
  labels:
    app: wineinfo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wineinfo-frontend
  template:
    metadata:
      labels:
        app: wineinfo-frontend
    spec:
      containers:
      - name: wineinfo-frontend
        image: jct_http_server:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: VITE_BACKEND
            value: "http://wineinfo-backend"
---
apiVersion: v1
kind: Service
metadata:
  name: wineinfo-frontend
spec:
  type: ClusterIP
  selector:
    app: wineinfo-frontend
  ports:
    - port: 3000
      targetPort: 3000
