apiVersion: apps/v1
kind: Deployment
metadata:
  name: wineinfo-backend
  labels:
    app: wineinfo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wineinfo-backend
  template:
    metadata:
      labels:
        app: wineinfo-backend
    spec:
      containers:
      - name: wineinfo-backend
        image: jct_http_server:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: CATALOG_SERVICE
            value: "http://wineinfo-catalog"
          - name: SEARCH_SERVICE
            value: "http://wineinfo-search"
          - name: RECS_SERVICE
            value: "http://wineinfo-recs"
---
apiVersion: v1
kind: Service
metadata:
  name: wineinfo-backend
spec:
  type: ClusterIP
  selector:
    app: wineinfo-backend
  ports:
    - port: 80
      targetPort: 8000
